Controllers/KullaniciController.cs
using Blogsite.Filters;
using Blogsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogsite.Controllers
{
    [AuthFilter(2)]
    public class KullaniciController : Controller
    {
        BlogsiteEntities entity = new BlogsiteEntities();
        // GET: Kullanici
        public ActionResult Index()
        {
            int kullaniciId = Convert.ToInt32(Session["Kullanici_id"]);
            var Kullanici = (from k in entity.Kullanici where k.Kullanici_id == kullaniciId select k).FirstOrDefault();

            ViewBag.AdSoyad = Kullanici.Ad + "  " + Kullanici.Soyad;
            ViewBag.EPosta = Kullanici.EPosta;
            ViewBag.TelefonNo = Kullanici.TelefonNo;
            return View();
        }

        [HttpGet]
        public ActionResult Anasayfa()
        {
            var blog = (from b in entity.Blog
                        join k in entity.Kategori on b.Kategori_id equals k.Kategori_id
                        select b).ToList();

            return View(blog);
        }

        [HttpPost]
        public ActionResult Anasayfa(FormCollection fc)
        {
            int blogId = Convert.ToInt32(fc["Blog_id"]);

            var blog = (from b in entity.Blog where b.Blog_id == blogId select b).ToList();

            return RedirectToAction("BlogIcerik", new { id = blogId });
        }
        public ActionResult BlogIcerik(int id)
        {
            var blog = (from b in entity.Blog
                        where b.Blog_id == id
                        select b).FirstOrDefault();

            return View(blog);
        }
    }

}

Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogsite.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        public ActionResult Index()
        {
            Session.Abandon();

            return RedirectToAction("Index","Login");
        }
    }
}

Controllers/SifreController.cs
using Blogsite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blogsite.Controllers
{
    public class SifreController : Controller
    {
        BlogsiteEntities entity = new BlogsiteEntities();
        // GET: Sifre
        public ActionResult Index()
        {
            int kullanici_id = Convert.ToInt32(Session["Kullanici_id"]);

            if (kullanici_id == 0) return RedirectToAction("Index", "login");

            var kullanici=(from k in entity.Kullanici where k.Kullanici_id == kullanici_id select k).FirstOrDefault();

            ViewBag.mesaj = null;
            ViewBag.stil=null;
            ViewBag.yethiTurId=null;

            return View(kullanici);
        }

        [HttpPost]
        public ActionResult Index(int Kullanici_id, string eskiParola,string yeniParola,string yeniParolaKontrol)
        {
            var kullanici=(from k in entity.Kullanici where k.Kullanici_id==Kullanici_id select k).FirstOrDefault();

            if (eskiParola!=kullanici.KullaniciParola)
            {
                ViewBag.mesaj = "Eski parolanızı kontrol ediniz.";
                ViewBag.stil = "alert alert-danger";
                return View(kullanici);
            }
            if (yeniParola != yeniParolaKontrol)
            {
                ViewBag.mesaj = "Yeni parola ve yeni parola tekrarı eşleşmedi.";
                ViewBag.stil = "alert alert-danger";
                return View(kullanici);
            }
            if (yeniParola.Length<6 || yeniParola.Length>15)
            {
                ViewBag.mesaj = "Yeni parola en az 6 karakter en çok 15 karakter olmalı";
                ViewBag.stil = "alert alert-danger";
                return View(kullanici);
            }

            kullanici.KullaniciParola = yeniParola;
            entity.SaveChanges();

            ViewBag.mesaj = "Parolanız başarıyla değiştirildi.";
            ViewBag.stil = "alert alert-success";
            ViewBag.yetkiTurId = kullanici.KullaniciYetkiTur_id;

            return View(kullanici);
            // TempData["bilgi"]=

        }
    }
}

Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager mt-5">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li class="page-item">
                <a class="page-link"  href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li class="page-item"><a class="page-link"  href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="page-item active"><span class="page-link" >@i</span></li>
            }
            else
            {
            <li class="page-item"><a class="page-link"  href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li class="page-item"><a class="page-link"  href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li class="page-item"><a class="page-link"  href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li class="page-item"><a class="page-link"  href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/navbar.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/gridmvc.js"></script>
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a91e5f7e14.js" crossorigin="anonymous"></script>
</head>
<body class="bg-dark" >
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
        <div class="container">
            <a class="navbar-brand">Admin Paneli</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Anasayfa", "Admin", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Kategori İşlemleri", "Kategoriler", "Admin", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="dropdown mt-2">
                        <a href="#" class="nav-item text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Blog İşlemleri</a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-item ">  @Html.ActionLink("Blog Ekle", "BlogEkle", "Admin", new { }, new { @style = "color:black;text-decoration:none" })</li>
                            <li class="dropdown-item "> @Html.ActionLink("Blog Listele", "Blog", "Admin", new { }, new { @style = "color:black;text-decoration:none" })</li>
                            <li class="dropdown-item "> @Html.ActionLink("Blog Sil Güncelle", "BlogSilGuncelle", "Admin", new { }, new { @style = "color:black;text-decoration:none" })</li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Log İşlemleri", "Log", "Admin", new { }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
                @Html.ActionLink("İletişime Geçin", "Index", "Admin", new { }, new { @class = "nav-link" })
            </li>*@
                </ul>
                @*<form class="d-flex" role="search">
            <input class="form-control me-2 m-2" type="search" placeholder="Ara" aria-label="Search">
        </form>*@
                <div class="dropdown text-end ">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle fa-2x" style="color:white"></i>
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li class="dropdown-item ">@Html.ActionLink("Hesabım", "Index", "Admin", new { }, new { @class = "nav-link" })</li>
                        <li class="dropdown-item ">@Html.ActionLink("Şifre Değiştir", "Index", "Sifre", new { }, new { style = "color:black;text-decoration:none" })</li>
                        <li><hr class="dropdown-divider"></li>
                        <li class="dropdown-item"> @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { style = "color:black;text-decoration:none" })</li>
                    </ul>
                </div>

            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

Views/Shared/_LayoutKullanici.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/navbar.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a91e5f7e14.js" crossorigin="anonymous"></script>
</head>
<body class="bg-dark">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
        <div class="container">
            <a class="navbar-brand" href="">Hoşgeldiniz</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Anasayfa", "Kullanici", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-circle fa-2x" style="color:white"></i>
                    </a>
                    <ul class="dropdown-menu text-small">
                        <li class="dropdown-item ">@Html.ActionLink("Hesabım", "Index", "Kullanici", new { }, new { @class = "nav-link" })</li>
                        <li class="dropdown-item ">@Html.ActionLink("Şifre Değiştir", "Index", "Sifre", new { }, new { style = "color:black;text-decoration:none" })</li>
                        <li><hr class="dropdown-divider"></li>
                        <li class="dropdown-item"> @Html.ActionLink("Çıkış", "Index", "Logout", new { }, new { style = "color:black;text-decoration:none" })</li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>

Views/Shared/_LayoutMisafir.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/navbar.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/a91e5f7e14.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
        <div class="container">
            <a class="navbar-brand" href="#">Hoşgeldiniz</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Anasayfa", "Index", "Kullanici", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("İletişime Geçin", "Contact", "Kullanici", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <div class="d-flex nav-item">
                    @Html.ActionLink(" ", "Index", "Logout", new { }, new { @class = "fa-solid fa-user", style = "color:white;font-size:20px;text-decoration:none" })
                </div>
            </div>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>
</body>
</html>